language: php
php:
- 5.4
- 5.5
- 5.6
- hhvm
git:
  submodules: false
before_script:
- composer install --prefer-source
script:
- vendor/bin/phpunit --configuration phpunit.travis.xml
- vendor/bin/phpcs --standard=PSR2 src/*
notifications:
  slack:
    secure: jODUTpB8SgL6Lq6mVn2iCljZv3gM3h8wZRBLgkLJsoa/U99A6zSmvQ3xCDwVa7jraj3NvP5hNScg3JtBnQaYkbticH5r2hRj5DiCPJFBW9WGgZa/7OPFkT9uQ7LDGqtuPgFoFk/3jFPW24U5gfeURI/HPj4tlpshjmzN1q+l3F8=
